version: '4'

services:
  mongodb:
    image: mongo:7.0.5  # Correct version (7.8.5 does not exist as of now)
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
